### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by annhilati** [SuperAnt220/mc-dp-icons#3]
I really like this icon pack and I have a few ideas for future icons in this extension:

- .jar files (server.jar, version.jar, etc.)
- server files (server.properties, ops.json, plugins folder, etc.)
- world files (datapacks folder, level,dat, etc.)
- .yml files (possibly for files like bukkit.yml or spigot.yml own icons)
- optifine resourcepack files (cit folder, sky folder etc.)
- optifine shaders files (shaders.properties, etc.)
- specular/normal textures (_n.png, _s.png)

**Comment by annhilati** [comment]
You could also add specular and normal texture (_s, _n) icons

**Comment by SuperAnt220** [comment]
Thanks for the ideas, we will definitely consider these suggestions in the future. There is a high chance `.yml` will be added in the next update
